services:
  - type: web
    name: ws-server
    env: node
    plan: free
    buildCommand: npm install && node download-models.js
    startCommand: node server.js
    healthCheckPath: /health
    envVars:
      - key: API_KEY
        value: 57271a26c9cf4eeec7fe46a91f2f4c81
      - key: NODE_ENV
        value: production
